version: '3.8'

services:
  fasttrack:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    container_name: fasttrack-app
    ports:
      - "3004:80"
    volumes:
      - fasttrack-data:/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data/app_data
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-fasttrack-production-secret-change-this-in-production}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fasttrack.rule=Host(`fasttrack.localhost`)"
      - "traefik.http.services.fasttrack.loadbalancer.server.port=80"

volumes:
  fasttrack-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/fasttrack-data

networks:
  default:
    name: fasttrack-network
